
class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        has = {}
        for c in s:
            if c in has:
                has[c] += 1
            else:
                has[c] = 1
        for c in t:
            if c in has:
                has[c] -= 1
                if has[c] < 0:
                    return c
            else:
                return c

s = 'abcd'
t = 'abcde' 
sol = Solution()
print sol.findTheDifference(s,t)

'''
no 389
digested 2/21/2017
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
'''
